### Get auth token
### Admin token: Authorization: Basic YWRtaW46YWRtaW4=
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Positive test: Admin can create new user with correct data
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "kate1998",
  "password": "Kate1998@",
  "role": "USER"
}

### Negative test: Admin cannot create new user with blank username
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "",
  "password": "{{$random.uuid}}",
  "role": "USER"
}

### Negative test: Admin cannot create new user with username 2 characters
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "ab",
  "password": "{{$random.uuid}}",
  "role": "USER"
}

### Negative test: Admin cannot create new user with username 16 characters
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "abqqqqqqqqqqqqqq",
  "password": "{{$random.uuid}}",
  "role": "USER"
}

### Negative test: Admin cannot create new user with username contains $%^&*()@# characters
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "$%^&*()@#",
  "password": "{{$random.uuid}}",
  "role": "USER"
}

### Negative test: Admin cannot create new user with blank password
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "{{$random.uuid}}",
  "password": "",
  "role": "USER"
}

### Negative test: Admin cannot create new user with password less than 8 characters
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "{{$random.uuid}}",
  "password": "1234567",
  "role": "USER"
}

### Negative test: Admin cannot create new user with password without digits
### Negative test: Admin cannot create new user with password without 1 lower case character
### Negative test: Admin cannot create new user with password without 1 upper case character
### Negative test: Admin cannot create new user with password without 1 special character
### Negative test: Admin cannot create new user with password with spaces
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "{{$random.uuid}}",
  "password": "ee",
  "role": "USER"
}

### Negative test: Admin cannot create new user with role not from List "ADMIN", "USER"
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "{{$random.uuid}}",
  "password": "{{$random.uuid}}",
  "role": "EDITOR"
}

### Positive test: Authorized user can create account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTg6S2F0ZTE5OThA

### Positive test: Account has been created
GET http://localhost:4111/api/v1/customer/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTg6S2F0ZTE5OThA

### Negative test: Create user that already exists
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "kate1998",
  "password": "Kate1998@",
  "role": "USER"
}


